"""quickbooks accounts and transaction link

Revision ID: 03f3cc32d8e7
Revises: 89bee9b8a115
Create Date: 2026-08-01 23:43:20.215629
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '03f3cc32d8e7'
down_revision: str | None = '89bee9b8a115'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbo_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qbo_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fully_qualified_name', sa.String(length=512), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('account_sub_type', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qbo_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qbo_txn_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('qbo_txn_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('qbo_sync_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('qbo_attachment_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('qbo_matched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qbo_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qbo_sync_error', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_category_account_id', 'qbo_accounts', ['category_account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_category_account_id', type_='foreignkey')
        batch_op.drop_column('qbo_sync_error')
        batch_op.drop_column('qbo_synced_at')
        batch_op.drop_column('qbo_matched_at')
        batch_op.drop_column('qbo_attachment_id')
        batch_op.drop_column('qbo_sync_token')
        batch_op.drop_column('qbo_txn_type')
        batch_op.drop_column('qbo_txn_id')
        batch_op.drop_column('category_account_id')

    op.drop_table('qbo_accounts')
    # ### end Alembic commands ###
