"""totp pending session flag

Revision ID: 5997c47d8d5f
Revises: cb5ffa3263b1
Create Date: 2026-07-28 22:12:08.666417
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5997c47d8d5f'
down_revision: str | None = 'cb5ffa3263b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default is required, not cosmetic: adding a NOT NULL column to a
    # table that already has rows fails outright on SQLite without one. Existing
    # sessions predate TOTP, so false (already past the second factor) is both
    # correct and the safe default — it does not lock anyone out mid-session.
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "totp_pending",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('totp_pending')

    # ### end Alembic commands ###
